version: "3"

services:
  app:
    build:
      context: .

      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    command: make test
    image: timetocodesomething/devops-for-developers-project-74